stages:
  - clean
  - deploy

cleanup_build:
  stage: clean
  script:
  - docker stop xen-backup
  - docker rm xen-backup
  - docker rmi xenserver_backup

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  when: always