before_script:
  - docker stop xenbackup
  - docker rm xenbackup

job1:
  stage: deploy
  script:
    - docker build -t xenserver-backup .
    - docker run -d -p 5001:5001 --network="bridge" --name xenbackup xenserver-backup